<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BesersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataBeser = [
            ["indonesia"=>"anjing","beser"=>"nofan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"air","beser"=>"waer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"agas","beser"=>"raprap","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"adegan","beser"=>"roifuer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ada","beser"=>"naisi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"anak","beser"=>"mkun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ayah","beser"=>"omsinan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ajaran","beser"=>"farkarkor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"alis","beser"=>"mkawur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"angin","beser"=>"wayem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"asap","beser"=>"ipai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"awas","beser"=>"jaka","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"aku","beser"=>"aya","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ambilkan","beser"=>"wun ita","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"apakah","beser"=>"inema yo","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"babi","beser"=>"beyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bagus","beser"=>"iwye","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"baju","beser"=>"tantun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bakar","beser"=>"tabrai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bangun","beser"=>"wakwoek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bantal","beser"=>"afyak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bapak","beser"=>"omsinan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bau","beser"=>"ifnarem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"begini","beser"=>"wetne","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"belakang","beser"=>"worpur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"belanja","beser"=>"tkaukowet","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"beli","beser"=>"kwout","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"belum","beser"=>"waniem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"benar","beser"=>"kaku","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"berisik","beser"=>"fandwent","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"besok","beser"=>"mehnama","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bintang","beser"=>"mak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bisa","beser"=>"dadi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"buaya","beser"=>"ongkor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"bulan","beser"=>"payek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"burung","beser"=>"man","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cahaya","beser"=>"ihnai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cair","beser"=>"opromt","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cocok","beser"=>"itrow","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"coba","beser"=>"ifnak tat","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cela","beser"=>"pak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cecak","beser"=>"ampnier","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cicak","beser"=>"ampnir","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"coki","beser"=>"coki","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cari","beser"=>"twerf","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cerita","beser"=>"wawawot","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cangkir","beser"=>"mok","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cabe","beser"=>"maritan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"cagang","beser"=>"muyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"duduk","beser"=>"kyain","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"dia","beser"=>"iri","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"daun","beser"=>"uram","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"desa","beser"=>"mnu","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"duri","beser"=>"borek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"didalam","beser"=>"dori","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"dialog","beser"=>"watwot","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"engkau","beser"=>"au","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"eyang","beser"=>"omsinan bar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ekor","beser"=>"pura","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"enam","beser"=>"wonem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"entah","beser"=>"kofawi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"enak","beser"=>"nannauye","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"empat","beser"=>"fyak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"entah","beser"=>"kofawiwa","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gajian","beser"=>"tun pipi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gembira","beser"=>"iryaw","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gelap","beser"=>"pawe","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gigi","beser"=>"nakoer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"geli","beser"=>"yayien","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gemuk","beser"=>"iba","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gampang","beser"=>"ipyan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gagak","beser"=>"mankwau","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"gementar","beser"=>"ryadai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hujan","beser"=>"mekem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hati","beser"=>"ken","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hari ini","beser"=>"rahne","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hidup","beser"=>"kemn","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hidung","beser"=>"hnonukor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hampir","beser"=>"kermkun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hantu","beser"=>"manweyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hitam","beser"=>"ipaitem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hiu","beser"=>"romun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kemarin","beser"=>"mandowndi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"hutan","beser"=>"tub","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ikan","beser"=>"iyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"indah","beser"=>"iyama","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ibu","beser"=>"kinaek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ingat","beser"=>"watwar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ibadah","beser"=>"nadi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ikut","beser"=>"yato","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"imbalan","beser"=>"wakwak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ingatan","beser"=>"twarepen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ingin","beser"=>"yarmom","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ingus","beser"=>"mnoer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ipar","beser"=>"bati","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"iri","beser"=>"yarmomn wa","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"isap","beser"=>"toft","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"isi","beser"=>"water","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"istri","beser"=>"kinak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"itu","beser"=>"iya","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"iya","beser"=>"imbo","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ibarat","beser"=>"imnit","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jualan","beser"=>"wawow","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jalan","beser"=>"nyan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jalur","beser"=>"mou","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jangan","beser"=>"dawe","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jangkar","beser"=>"nyoer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jantung","beser"=>"barmor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jatuh","beser"=>"itapi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jauh","beser"=>"wyingkwaen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jebol","beser"=>"pak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"jeruk","beser"=>"ingkrai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kami","beser"=>"ingko","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"karna","beser"=>"kukr","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kain","beser"=>"trei","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kakak","beser"=>"naek iba","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kakek","beser"=>"aput sinan i","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kaki","beser"=>"wempin","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kampung","beser"=>"mnu","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kamu","beser"=>"au","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kapak","beser"=>"mkan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kapur","beser"=>"afer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kebun","beser"=>"yaef","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kecil","beser"=>"ibawa","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kelapa","beser"=>"trai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kentut","beser"=>"oku","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kita","beser"=>"ko","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kincing","beser"=>"tortor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kotoran","beser"=>"paput","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kuah","beser"=>"dur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kuat","beser"=>"rarwaet","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"kucin","beser"=>"pus","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lagi","beser"=>"we","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lain","beser"=>"iwete","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"laju","beser"=>"imbrar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"laki-laki","beser"=>"hnoman","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lalat","beser"=>"rap-rap","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lebah","beser"=>"nyiwer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lebar","beser"=>"iwaem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"leher","beser"=>"tatukoer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lemon","beser"=>"ingkrai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lepas","beser"=>"ikfit","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lidah","beser"=>"ramar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lihat","beser"=>"mayem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lipat","beser"=>"waper","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lima","beser"=>"rim","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lompat","beser"=>"rwop","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"luar","beser"=>"wondi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lubang","beser"=>"pak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"luka","beser"=>"par","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"lusa","beser"=>"metr iyama","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"mama","beser"=>"omkinak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"mabuk","beser"=>"imter","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"macam","beser"=>"kokimit","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"main","beser"=>"ifnak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"meledak","beser"=>"imyef","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"melompot","beser"=>"ryop","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"memasak","beser"=>"tkangkun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"memakan","beser"=>"tan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"menyelam","beser"=>"darapen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"minggir","beser"=>"warir","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"minta","beser"=>"weor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"minum","beser"=>"winem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"mono","beser"=>"iwawot wa","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"moncong","beser"=>"worpon","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"mulut","beser"=>"twadon","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"mundur","beser"=>"watutu","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"muntah","beser"=>"aworem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"naik","beser"=>"wawer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"nama","beser"=>"hnon-hnon","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"nasi","beser"=>"fat","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"nana","beser"=>"nan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"nenek","beser"=>"aput kinak i","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"objek","beser"=>"karajan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"oleng","beser"=>"ikarandeyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ombak","beser"=>"raryaen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"otak","beser"=>"angfnur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ompong","beser"=>"narpak","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pakaian","beser"=>"tantun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"padam","beser"=>"imar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pagi","beser"=>"arwo","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pahit","beser"=>"syarmar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pecah","beser"=>"imyef","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pedis","beser"=>"naryaen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pelang","beser"=>"awawen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pencuri","beser"=>"inamarna","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pinang","beser"=>"beren","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pindah","beser"=>"warir","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pintu","beser"=>"kangkeen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pisang","beser"=>"imbyef","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pohon","beser"=>"ai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"potong","beser"=>"perem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pukul","beser"=>"mun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pulang","beser"=>"wabur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"pulau","beser"=>"myoet","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"putar","beser"=>"itwir","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"putih","beser"=>"ipyoper","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"putus","beser"=>"imuk","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"radar","beser"=>"radar","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"rajin","beser"=>"imyaren","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"rambut","beser"=>"hnombram","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"rica","beser"=>"maritan","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ribut","beser"=>"fandwenet","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"rumah","beser"=>"rum","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"saya","beser"=>"aya","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sayur","beser"=>"tuf","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sembayang","beser"=>"ari","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sembuh","beser"=>"imnai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sembilan","beser"=>"wonem","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sepuluh","beser"=>"tangfur","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"siapa","beser"=>"mandiri","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"simpan","beser"=>"ikram","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"siang","beser"=>"ihnai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sore","beser"=>"mandira","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sombar","beser"=>"kadawuen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sombong","beser"=>"fyauman","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"supaya","beser"=>"intamaidoyo","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sudah","beser"=>"akwa","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"sumbat","beser"=>"twotepmn","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tai","beser"=>"kapu","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tanya","beser"=>"wafuken","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tangan","beser"=>"wramin","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tempat","beser"=>"mou","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"terima","beser"=>"wuyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tetapi","beser"=>"kama","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tiup","beser"=>"wawuf","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"timba","beser"=>"pot","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tombak","beser"=>"afen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tuhan","beser"=>"manteren","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"tuli","beser"=>"ipro","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"uang","beser"=>"pipi","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"uap","beser"=>"ipai","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ubah","beser"=>"tfadweyer","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ubi","beser"=>"mandarat","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ujung","beser"=>"mun","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"ular","beser"=>"ikaek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"undur","beser"=>"tu-tu","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"upah","beser"=>"ryo twuk","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"urat","beser"=>"wurek","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"uring","beser"=>"tortor","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"wangi","beser"=>"ifnarm we iwye","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"wanita","beser"=>"biyen","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"wilayah","beser"=>"mou","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"waspada","beser"=>"mkojaka","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"yesus","beser"=>"manteren","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime],
            ["indonesia"=>"yaitu","beser"=>"iyama","user_id"=>"1","created_at"=>new \DateTime,"updated_at"=>new \DateTime]
        ];

        \DB::table('besers')->insert($dataBeser);
    }
}
